# Generated by Django 2.0.5 on 2018-12-04 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('phon', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billId', models.AutoField(primary_key=True, serialize=False)),
                ('addres', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=10)),
                ('apm', models.CharField(max_length=6)),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FastFood',
            fields=[
                ('Name', models.CharField(max_length=12)),
                ('phon', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('imgs', models.CharField(max_length=30)),
                ('imgs_1', models.CharField(max_length=30)),
                ('sty', models.CharField(default=0, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('ShopName', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Shop_Img', models.CharField(default=1, max_length=2)),
                ('addres', models.CharField(max_length=30)),
                ('Shop_text', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='FastPhon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.FastFood'),
        ),
        migrations.AddField(
            model_name='bill',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Shop'),
        ),
    ]
