# Generated by Django 2.0.5 on 2018-12-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='m',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
