# Generated by Django 2.0.5 on 2018-12-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_auto_20181204_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='Shop_Img',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
