# Generated by Django 2.0.5 on 2018-12-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_auto_20181204_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastfood',
            name='sty',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
