# Generated by Django 2.0.5 on 2018-12-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_auto_20181204_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastfood',
            name='imgs',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='imgs_1',
            field=models.CharField(max_length=60),
        ),
    ]
