# Generated by Django 2.0.5 on 2018-12-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0009_bill_sty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='FastPhon_id',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
