# Generated by Django 2.0.5 on 2018-12-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0010_auto_20181205_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Get',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
