# Generated by Django 2.0.5 on 2018-12-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0012_auto_20181205_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='fraction',
            field=models.CharField(default='3.0', max_length=4),
        ),
    ]
