# Generated by Django 2.0.5 on 2018-12-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0013_shop_fraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='phon',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='fastfood',
            old_name='phon',
            new_name='phone',
        ),
    ]
