# Generated by Django 2.0.5 on 2018-12-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0014_auto_20181208_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastfood',
            name='imgs',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='fastfood',
            name='imgs_1',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
